# Generated by Django 3.2.3 on 2021-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='reportSubject',
            field=models.CharField(default='', help_text='What are you reporting about?', max_length=20, verbose_name='Report Title'),
        ),
    ]
