# Generated by Django 3.2.3 on 2021-11-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_disasterreport_reportsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterreport',
            name='disasterID',
        ),
    ]
