# Generated by Django 3.2.3 on 2021-11-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0003_remove_disasterreport_disasterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterreport',
            name='userID',
        ),
    ]
