# Generated by Django 4.0.1 on 2022-01-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0006_alter_disaster_cloudearly_alter_disaster_cloudlate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='cloudEarly',
            field=models.IntegerField(verbose_name='Cloud 9 AM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='cloudLate',
            field=models.IntegerField(verbose_name='Cloud 3 PM'),
        ),
    ]
