# Generated by Django 4.0.1 on 2022-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0007_alter_disaster_cloudearly_alter_disaster_cloudlate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='evaporation',
            field=models.IntegerField(verbose_name='Evaporation'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='humidityEarly',
            field=models.IntegerField(verbose_name='Humidity 9 AM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='humidityLate',
            field=models.IntegerField(verbose_name='Humidity 3 PM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='maxTemp',
            field=models.IntegerField(verbose_name='Maximum Temperature'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='minTemp',
            field=models.IntegerField(verbose_name='Minimum Temperature'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='pressureEarly',
            field=models.IntegerField(verbose_name='Pressure 9 AM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='pressureLate',
            field=models.IntegerField(verbose_name='Pressure 3 PM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='rainfall',
            field=models.IntegerField(verbose_name='Rainfall'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='sunshine',
            field=models.IntegerField(verbose_name='Sunshine'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='windDirEarly',
            field=models.IntegerField(verbose_name='Wind Direction 9 AM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='windDirLate',
            field=models.IntegerField(verbose_name='Wind Direction 3 PM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='windGustDir',
            field=models.IntegerField(verbose_name='Wind Gust'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='windGustSpeed',
            field=models.IntegerField(verbose_name='WindGustSpeed'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='windSpeedEarly',
            field=models.IntegerField(verbose_name='Wind Speed 9 AM'),
        ),
        migrations.AlterField(
            model_name='disaster',
            name='windSpeedLate',
            field=models.IntegerField(verbose_name='Wind Speed 3 PM'),
        ),
    ]
